#spring:
#  application:
#    name: service-edu
#  profiles:
#    active: dev
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/onlinecolleges?
#      serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: 123456
#
#server:
#  port: 8080
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#
#
#mapper-locations: classpath:com/atguigu/service/ */mapper/*.xml
#
